apiVersion: v1
kind: Secret

metadata:
  name: keycloak-secret
  namespace: revenda

type: Opaque

stringData:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin

  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin