apiVersion: apps/v1
kind: Deployment

metadata:
  name: keycloak-postgres
  namespace: revenda

spec:
  replicas: 1

  selector:
    matchLabels:
      app: keycloak-postgres

  template:

    metadata:
      labels:
        app: keycloak-postgres

    spec:

      containers:

        - name: postgres

          image: postgres:15

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_PASSWORD

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"

            initialDelaySeconds: 5
            periodSeconds: 5
