apiVersion: apps/v1
kind: Deployment

metadata:
  name: keycloak
  namespace: revenda

spec:
  replicas: 1

  selector:
    matchLabels:
      app: keycloak

  template:

    metadata:
      labels:
        app: keycloak

    spec:

      containers:

        - name: keycloak

          image: quay.io/keycloak/keycloak:26.3.5

          command:
            - /opt/keycloak/bin/kc.sh

          args:
            - start-dev
            - --import-realm

          ports:
            - containerPort: 8080

          env:

            - name: KC_DB
              value: postgres

            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: POSTGRES_HOST

            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: POSTGRES_DB

            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_USER

            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: POSTGRES_PASSWORD

            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_BOOTSTRAP_ADMIN_USERNAME

            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_BOOTSTRAP_ADMIN_PASSWORD

          volumeMounts:

            - name: realm
              mountPath: /opt/keycloak/data/import

      volumes:

        - name: realm

          configMap:
            name: keycloak-realm